### ISSUE TITLE
Specify IP address via env variables

### ISSUE THREAD

**Issue by kovetskiy** [Flagsmith/react-native-performance-monitor#22]
Hey, thanks for the tool, just tested it on android emulator. There should be an option to specify a custom IP address instead of 127.0.0.1 using environment variables. Specifying IP address even via the third parameter is too much.

**Comment by kyle-ssg** [comment]
Sure, I do agree that parameters were just added as more were needed, I can't devote too much time to the project but I'd be happy to accept a pr and bump a major version with better thought out parameters.

**Comment by kyle-ssg** [comment]
Since you can already do this in the parameters of withPerformanceMonitor, the solution would be to use react-native-config in combination with this library.
