### ISSUE TITLE
Not getting option to remount, or set baseline in http://127.0.0.1:8125/

### ISSUE THREAD

**Issue by ShruthiRSalian** [Flagsmith/react-native-performance-monitor#35]
After running below command, 
npx react-native-performance-monitor get

http://127.0.0.1:8125/ page gets loaded, but I am not getting option to remount, or set baseline in http://127.0.0.1:8125/.
Can you help me with detailed steps.

Thanks...

**Comment by kyle-ssg** [comment]
This seems to suggest that you're not wrapping any components with the provider.

```
import withPerformance from 'react-native-performance-monitor/provider'
withPerformance(App) 
```

Adding this and refreshing your app, you should see the graph get populated.
