### ISSUE TITLE
How to add this with redux integrated project

### ISSUE THREAD

**Issue by akiladevinda** [Flagsmith/react-native-performance-monitor#38]
Hi, thanks for this awesome tool that can monitor performance in react native.
Would like to know how to use this with redux? How to connect?

My current codebase sample

`export default connect(mapStateToProps, mapDispatchToProps)(React.memo(Router));`

**Comment by lffloyd** [comment]
Hi @akiladevinda , I've got this working by doing the following:

```ts
const connectedCatalogList = connect(mapStateToProp)(CatalogList);
export default withPerformanceMonitor(connectedCatalogList, 'CatalogList', '192.168.0.8'); //this is my machine ip
```

So, instead of exporting the connected component as default, I exported the HOC with the injected performance monitor.

**Comment by kyle-ssg** [comment]
Yep above makes sense, when it comes down to it a connected component is still a component.
