### ISSUE TITLE
Is this library up to date ? 

### ISSUE THREAD

**Issue by dogabudak** [Flagsmith/react-native-performance-monitor#69]
Hey Flagsmith team,I have been using your open source libraries a lot and I really enjoy them, but lately I have seen that you are not updating some of them. This library is not updated for a long time and I wanted to ask if its a dead library or are you planing to merge PR's soon ? As an example I made this one here but i got no comments or anything so far, https://github.com/Flagsmith/react-native-performance-monitor/pull/39

I was going to add types which is specified here https://github.com/Flagsmith/react-native-performance-monitor/issues/7, since i am using it a lot and i would like to see some types in this library, it would be really helpful but i dont want to invest time on it if its going to be ignored,

Thanks a lot

**Comment by kyle-ssg** [comment]
Hey @dogabudak, thanks for taking the time to write this. 

I use this library quite actively so yes I do plan on maintaining it, almost all of the PRs are automated dependencies and as a result, I've missed this one so I apologise. I'll review this PR Today

**Comment by kyle-ssg** [comment]
Released in 2.0.0, the only change was I made _id ``id``
